server:
  port: 8081

#spring:
#  data:
#    cassandra:
#      port: 9042
#      keyspace-name: reactive_cassandra
#      contact-points: localhost
#      schema-action: create_if_not_exists
#      local-datacenter:datacenter1
